exclude: ^\.idea$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.50.0"
    hooks:
      - id: eslint
        args: ["--fix"]
        additional_dependencies:
          - "eslint@8.24.0"
          - "eslint-plugin-react"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint-config-prettier"
          - "eslint-plugin-prettier"
          - "eslint-plugin-react"
          - "eslint-plugin-react-hooks"
